import { spawnSync } from "child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname } from "path";
import { paths } from "./paths.js";
import type { InstallProvider } from "./cli.js";

// --- Claude Code installation ---

const HOOK_EVENTS = [
  "SessionStart",
  "SessionEnd",
  "PreToolUse",
  "PostToolUse",
  "Stop",
  "Notification",
  "UserPromptSubmit",
] as const;

const CCWATCH_HOOK = { type: "command" as const, command: "ccwatch hook" };

interface HookEntry {
  matcher?: string;
  hooks: { type: string; command?: string; prompt?: string; timeout?: number }[];
}

function hasCcwatchHook(entries: HookEntry[]): boolean {
  return entries.some((entry) =>
    entry.hooks.some((h) => h.type === "command" && h.command === "ccwatch hook")
  );
}

async function installClaude(): Promise<void> {
  console.log("Installing ccwatch for Claude Code...\n");

  // Read existing settings
  let settings: Record<string, unknown> = {};

  if (existsSync(paths.claude.settings)) {
    try {
      settings = JSON.parse(readFileSync(paths.claude.settings, "utf-8"));
    } catch (e) {
      console.error(`Error reading ${paths.claude.settings}: ${e}`);
      process.exit(1);
    }
  } else {
    mkdirSync(dirname(paths.claude.settings), { recursive: true });
  }

  // Merge hooks -- nested under "hooks" key in settings.json
  let hooksAdded = 0;

  // Remove any stale top-level hook keys from previous installs
  for (const event of HOOK_EVENTS) {
    if (event in settings) {
      delete settings[event];
    }
  }

  const hooksObj = (settings.hooks ?? {}) as Record<string, HookEntry[]>;
  settings.hooks = hooksObj;

  for (const event of HOOK_EVENTS) {
    const existing = hooksObj[event] ?? [];

    if (hasCcwatchHook(existing)) {
      console.log(`  \u2713 ${event} hook already installed`);
      continue;
    }

    const hookEntry: HookEntry =
      event === "PreToolUse" || event === "PostToolUse"
        ? { matcher: ".*", hooks: [CCWATCH_HOOK] }
        : { hooks: [CCWATCH_HOOK] };

    existing.push(hookEntry);
    hooksObj[event] = existing;
    hooksAdded++;
    console.log(`  + ${event} hook added`);
  }

  // Status line
  const existingStatus = settings.statusLine as { command?: string } | undefined;
  if (existingStatus?.command === "ccwatch status") {
    console.log(`  \u2713 statusLine already configured`);
  } else if (existingStatus) {
    console.log(
      `  \u26A0 statusLine already set to: ${existingStatus.command ?? JSON.stringify(existingStatus)}`
    );
    console.log(`    Replace with 'ccwatch status'? Updating...`);
    settings.statusLine = { type: "command", command: "ccwatch status" };
  } else {
    settings.statusLine = { type: "command", command: "ccwatch status" };
    console.log(`  + statusLine configured`);
  }

  // Write back
  writeFileSync(paths.claude.settings, JSON.stringify(settings, null, 2) + "\n");

  console.log(`\nSettings written to ${paths.claude.settings}`);
  if (hooksAdded > 0) {
    console.log(`${hooksAdded} hook(s) added.`);
  }

  console.log("\nDone! Start ccwatch in one terminal, then use Claude Code in another.");
}

// --- OpenCode installation ---

/**
 * The OpenCode plugin source that gets written to ~/.config/opencode/plugins/ccwatch-plugin.js.
 * This plugin subscribes to OpenCode's event system and writes session JSON files
 * to ~/.config/ccwatch/sessions/ in the same format as the Claude Code hooks.
 */
const OPENCODE_PLUGIN_SOURCE = `// ccwatch plugin for OpenCode — auto-generated by 'ccwatch install --provider opencode'
// Do not edit manually. Re-run 'ccwatch install --provider opencode' to update.

import { join } from "path";
import { homedir } from "os";
import { existsSync, mkdirSync, readFileSync, writeFileSync, unlinkSync } from "fs";

const SESSIONS_DIR = join(homedir(), ".config", "ccwatch", "sessions");

function ensureSessionsDir() {
  if (!existsSync(SESSIONS_DIR)) {
    mkdirSync(SESSIONS_DIR, { recursive: true });
  }
}

function sessionFile(sessionId) {
  return join(SESSIONS_DIR, sessionId + ".json");
}

function readSession(sessionId) {
  const filePath = sessionFile(sessionId);
  if (!existsSync(filePath)) return undefined;
  try {
    return JSON.parse(readFileSync(filePath, "utf-8"));
  } catch {
    return undefined;
  }
}

function writeSession(session) {
  ensureSessionsDir();
  writeFileSync(sessionFile(session.sessionId), JSON.stringify(session) + "\\n");
}

function deleteSession(sessionId) {
  try {
    unlinkSync(sessionFile(sessionId));
  } catch {
    // already gone
  }
}

// Track active sessions for this OpenCode instance
const activeSessions = new Map();

function ensureSession(sessionId, directory, now) {
  if (activeSessions.has(sessionId)) return readSession(sessionId);
  activeSessions.set(sessionId, true);
  const existing = readSession(sessionId);
  if (existing) {
    // Update PID to current process (handles restarts where the old PID is dead)
    existing.pid = process.pid;
    writeSession(existing);
    return existing;
  }
  const session = {
    sessionId,
    provider: "opencode",
    cwd: directory || "",
    state: "working",
    costUsd: 0,
    contextPct: 0,
    startedAt: now,
    lastUpdatedAt: now,
    pid: process.pid,
  };
  writeSession(session);
  return session;
}

export const CCWatchPlugin = async ({ project, directory }) => {
  ensureSessionsDir();

  return {
    event: async ({ event }) => {
      const now = new Date().toISOString();
      // OpenCode events use top-level sessionID, not nested session.id
      const sessionId = event.properties?.sessionID;

      switch (event.type) {
        case "session.created":
        case "session.updated": {
          if (!sessionId) break;
          const session = ensureSession(sessionId, directory, now);
          if (!session) break;
          // Extract cost, tokens, and model info from session info.
          // session.updated on the bus carries the full session snapshot
          // from the DB, so info.cost is the authoritative cumulative total.
          const info = event.properties?.info;
          if (info) {
            if (info.cost > 0) session.costUsd = info.cost;
            if (info.model?.id) session.model = info.model.id;
            if (info.directory) session.cwd = info.directory;
            if (info.title) session.title = info.title;
            if (info.tokens) {
              const t = info.tokens;
              const totalTokens = (t.input || 0) + (t.output || 0) + (t.reasoning || 0)
                + (t.cache?.read || 0) + (t.cache?.write || 0);
              if (totalTokens > 0) session.contextTokens = totalTokens;
            }
          }
          session.lastUpdatedAt = now;
          writeSession(session);
          break;
        }

        case "session.deleted": {
          if (!sessionId) break;
          activeSessions.delete(sessionId);
          deleteSession(sessionId);
          break;
        }

        case "session.idle": {
          if (!sessionId) break;
          const existing = ensureSession(sessionId, directory, now);
          if (!existing) break;
          existing.state = "waiting:input";
          existing.currentTool = undefined;
          existing.lastUpdatedAt = now;
          writeSession(existing);
          break;
        }

        case "session.error": {
          if (!sessionId) break;
          const existing = readSession(sessionId);
          if (!existing) break;
          existing.state = "waiting:input";
          existing.currentTool = undefined;
          existing.lastUpdatedAt = now;
          writeSession(existing);
          break;
        }

        case "session.status": {
          if (!sessionId) break;
          const existing = ensureSession(sessionId, directory, now);
          if (!existing) break;
          const status = event.properties?.status;
          // OpenCode uses "busy" (not "running") for active state
          if (status?.type === "busy") {
            existing.state = "working";
          } else if (status?.type === "idle") {
            existing.state = "waiting:input";
          }
          existing.lastUpdatedAt = now;
          writeSession(existing);
          break;
        }

        case "permission.asked": {
          if (sessionId) {
            const existing = ensureSession(sessionId, directory, now);
            if (existing) {
              existing.state = "waiting:permission";
              existing.lastUpdatedAt = now;
              writeSession(existing);
            }
          }
          break;
        }

        case "permission.replied": {
          if (sessionId) {
            const existing = readSession(sessionId);
            if (existing && existing.state === "waiting:permission") {
              existing.state = "working";
              existing.lastUpdatedAt = now;
              writeSession(existing);
            }
          }
          break;
        }

        case "message.part.updated": {
          const part = event.properties?.part;
          if (!part || !sessionId) break;
          const existing = readSession(sessionId);
          if (!existing) break;
          if (part.type === "tool" && part.tool) {
            if (part.state?.status === "running" || part.state?.status === "pending") {
              existing.state = "working";
              existing.currentTool = part.tool;
            } else if (part.state?.status === "completed") {
              existing.currentTool = undefined;
            }
            existing.lastUpdatedAt = now;
            writeSession(existing);
          }
          break;
        }
      }
    },

    "tool.execute.before": async (input, output) => {
      const now = new Date().toISOString();
      for (const sessionId of activeSessions.keys()) {
        const existing = readSession(sessionId);
        if (!existing) continue;
        existing.state = "working";
        const toolName = input.tool || "";
        const detail = output.args?.filePath || output.args?.command || output.args?.pattern || output.args?.query || "";
        existing.currentTool = detail ? toolName + " " + detail : toolName;
        existing.lastUpdatedAt = now;
        writeSession(existing);
        break;
      }
    },

    "tool.execute.after": async (input, output) => {
      const now = new Date().toISOString();
      for (const sessionId of activeSessions.keys()) {
        const existing = readSession(sessionId);
        if (!existing) continue;
        existing.currentTool = undefined;
        existing.lastUpdatedAt = now;
        writeSession(existing);
        break;
      }
    },
  };
};
`;

async function installOpenCode(): Promise<void> {
  console.log("Installing ccwatch for OpenCode...\n");

  // Ensure the plugins directory exists
  mkdirSync(paths.opencode.pluginsDir, { recursive: true });

  // Check if plugin already exists
  if (existsSync(paths.opencode.pluginFile)) {
    console.log(`  \u26A0 Plugin file already exists at ${paths.opencode.pluginFile}`);
    console.log(`    Overwriting with latest version...`);
  }

  // Write the plugin file
  writeFileSync(paths.opencode.pluginFile, OPENCODE_PLUGIN_SOURCE);
  console.log(`  + Plugin written to ${paths.opencode.pluginFile}`);

  console.log(`\nDone! Start ccwatch in one terminal, then use OpenCode in another.`);
}

// --- Main install command ---

export async function installCommand(provider?: string): Promise<void> {
  if (!provider) {
    console.error("Error: --provider flag is required.\n");
    console.error("Usage: ccwatch install --provider <claude|opencode>\n");
    console.error("Supported providers:");
    console.error("  claude    - Install hooks in ~/.claude/settings.json");
    console.error("  opencode  - Install plugin in ~/.config/opencode/plugins/");
    process.exit(1);
  }

  switch (provider) {
    case "claude":
      await installClaude();
      break;
    case "opencode":
      await installOpenCode();
      break;
    default:
      console.error(`Error: unknown provider '${provider}'. Must be 'claude' or 'opencode'.`);
      process.exit(1);
  }

  // Check if ccwatch is in PATH
  const which = spawnSync("which", ["ccwatch"], { encoding: "utf-8" });
  if (which.status !== 0) {
    console.log(
      "\n\u26A0 'ccwatch' not found in PATH. Make sure to add the compiled binary to your PATH."
    );
    console.log("  Build with: bun run build");
    console.log("  Then copy the binary: cp ccwatch /usr/local/bin/");
  } else {
    console.log(`\nccwatch binary found at: ${String(which.stdout).trim()}`);
  }
}
